import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./components/header/Header";
import Providers from "./providers/providers";

const iranSans = localFont({
  src: [
    {
      path: "../../public/fonts/IRANSans/IRANSansX-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/IRANSans/IRANSansX-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/IRANSans/IRANSansX-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/IRANSans/IRANSansX-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranSans.className}`}>
        <Providers>
          <Header />
          <main className="bg-gray-100 text-gray-900 dark:bg-gray-900 dark:text-gray-100 transition-colors duration-500">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
